- name: install nginx
  become: yes
  apt:
    name:
      - nginx

- name: add discord-recruitment-bot setting
  become: yes
  template:
    src: ../files/discord-recruitment-bot.conf
    dest: /etc/nginx/conf.d/discord-recruitment-bot.conf
  notify: reload nginx setting

- name: add blog setting
  become: yes
  template:
    src: ../files/blog.conf
    dest: /etc/nginx/conf.d/blog.conf
  notify: reload nginx setting

- name: add dashboard setting
  become: yes
  template:
    src: ../files/dashboard.conf
    dest: /etc/nginx/conf.d/dashboard.conf
  notify: reload nginx setting
