- name: install required packages
  become: yes
  apt:
    name:
      - php
      - php-mysql
      - php-mbstring
      - php-fpm
      - php-gd

- name: check database exists
  become: yes
  shell: mysql -e 'show databases;' | grep -e '^wordpress$'
  changed_when: no
  ignore_errors: yes
  register: check_database_exists

- name: create database
  become: yes
  shell: mysql -e 'CREATE DATABASE wordpress DEFAULT CHARACTER SET utf8;'
  when: check_database_exists.rc != 0

- name: relax restrictions post_max_size in fpm/php.ini
  become: yes
  lineinfile:
    path: /etc/php/7.2/fpm/php.ini
    regexp: '^post_max_size ='
    line: post_max_size = 60M
  register: php_fpm_post_max_size

- name: relax restrictions upload_max_filesize in fpm/php.ini
  become: yes
  lineinfile:
    path: /etc/php/7.2/fpm/php.ini
    regexp: '^upload_max_filesize ='
    line: upload_max_filesize = 60M
  register: php_fpm_upload_max_filesize

- name: restart php-fpm
  become: yes
  service:
    name: php7.2-fpm
    state: restarted
  when: php_fpm_post_max_size.changed or php_fpm_upload_max_filesize.changed

- name: create directory
  become: yes
  file:
    path: /var/www/html/{{ wordpress_name }}
    state: directory
    mode: '0777'
  register: wordpress_directory

- name: download wordpress
  get_url:
    url: https://ja.wordpress.org/latest-ja.tar.gz
    dest: /tmp/latest-ja.tar.gz
  when: wordpress_directory is changed

- name: unarchive wordpress
  become: yes
  unarchive:
    src: /tmp/latest-ja.tar.gz
    dest: /var/www/html/{{ wordpress_name }}
    remote_src: yes
  when: wordpress_directory is changed

- name: change permission
  become: yes
  file:
    path: /var/www/html/{{ wordpress_name }}
    state: directory
    group: www-data
    owner: www-data
    recurse: yes
  when: wordpress_directory is changed
