- name: install required packages
  become: true
  apt:
    name:
      - php
      - php-mysql
      - php-mbstring
      - php-fpm
      - php-gd
      - php-zip
      - php-xml
      - php-bcmath
      - php-exif
      - php-imagick
      - php-mysqli
      - php-opcache
      - libfreetype6-dev
      - libjpeg-dev
      - libmagickwand-dev
      - libpng-dev
      - ghostscript

- name: check database exists
  become: true
  shell: mysql -e 'show databases;' | grep -e '^wordpress$'
  changed_when: no
  ignore_errors: true
  register: check_database_exists

- name: create database
  become: true
  shell: mysql -e 'CREATE DATABASE wordpress DEFAULT CHARACTER SET utf8;'
  when: check_database_exists.rc != 0

- name: relax restrictions post_max_size in fpm/php.ini
  become: true
  lineinfile:
    path: /etc/php/7.2/fpm/php.ini
    regexp: '^post_max_size ='
    line: post_max_size = 60M
  register: php_fpm_post_max_size

- name: relax restrictions upload_max_filesize in fpm/php.ini
  become: true
  lineinfile:
    path: /etc/php/7.2/fpm/php.ini
    regexp: '^upload_max_filesize ='
    line: upload_max_filesize = 60M
  register: php_fpm_upload_max_filesize

- name: restart php-fpm
  become: true
  service:
    name: php7.2-fpm
    state: restarted
  when: php_fpm_post_max_size.changed or php_fpm_upload_max_filesize.changed

- name: create directory
  become: true
  file:
    path: /var/www/html/{{ wordpress_name }}
    state: directory
    mode: '0777'
  register: wordpress_directory

- name: download wordpress
  get_url:
    url: https://ja.wordpress.org/latest-ja.tar.gz
    dest: /tmp/latest-ja.tar.gz
  when: wordpress_directory is changed

- name: unarchive wordpress
  become: true
  unarchive:
    src: /tmp/latest-ja.tar.gz
    dest: /var/www/html/{{ wordpress_name }}
    remote_src: true
  when: wordpress_directory is changed

- name: change permission
  become: true
  file:
    path: /var/www/html/{{ wordpress_name }}
    state: directory
    group: www-data
    owner: www-data
    recurse: true
  when: wordpress_directory is changed

- name: check wp command exists
  stat:
    path: /usr/local/bin/wp
  register: wp_command_exists

- name: install wp command
  become: true
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    mode: '0775'
  when: not wp_command_exists.stat.exists
