# sudo apt install -y default-jre
- name: install required packages
  become: true
  apt:
    name:
      - gnupg
      - default-jre

# wget -q -O - https://pkg.jenkins.io/debian/jenkins-ci.org.key | sudo apt-key add -
- name: add jenkins apt-key
  become: true
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins-ci.org.key

# sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
- name: add jenkins repository
  become: true
  apt_repository:
    repo: deb http://pkg.jenkins.io/debian-stable binary/

# sudo apt update
# sudo apt install -y jenkins
- name: install jenkins
  become: true
  apt:
    name:
      - jenkins
