- name: apt update
  become: yes
  apt:
    update_cache: yes

- name: install apt-file
  become: yes
  apt:
    name: apt-file

- name: apt-file update
  become: yes
  shell: apt-file update

- name: install some libraries
  become: yes
  apt:
    name:
      - git
      - gem
      - zlib1g-dev
      - libsqlite3-dev
      - autoconf
      - libxml2-dev
      - libxslt1-dev
      - libmysqlclient-dev
      - software-properties-common
      - g++
      - gcc
      - make

- name: set original bashrc
  copy:
    src: ../files/bashrc
    dest: ~/.bashrc

- name: install libsodium
  import_tasks: libsodium.yml
  tags: [libsodium]

- name: set locale Asia/Tokyo
  become: yes
  file:
    src: /usr/share/zoneinfo/Asia/Tokyo
    dest: /etc/localtime
    state: link
