- name: install some packages
  become: true
  apt:
    name:
      - tzdata # timezoneの指定に必要
      - libmysqlclient-dev # mysql2 gemをインストールするのに必要

- name: set locale Asia/Tokyo
  become: true
  file:
    src: /usr/share/zoneinfo/Asia/Tokyo
    dest: /etc/localtime
    state: link
