- name: setup environment variable
  copy:
    src: ../files/production_env
    dest: ~/.production_env

- name: load environment file when login
  lineinfile:
    path: ~/.ansible_preload
    line: source ~/.production_env
    create: yes
