- name: install python3
  become: true
  yum:
    name:
      - python3

- name: install supervisor
  become: true
  shell: pip3 install supervisor

- name: add supervisord.conf
  become: true
  template:
    src: ../files/supervisord.conf
    dest: /etc/supervisor/supervisord.conf

- name: add settings robotyosu.conf
  become: true
  template:
    src: ../files/conf.d/robotyosu.conf
    dest: /etc/supervisor/conf.d/robotyosu.conf

- name: add setting rfe.conf
  become: true
  template:
    src: ../files/conf.d/rfe.conf
    dest: /etc/supervisor/conf.d/rfe.conf

- name: kill supervisord
  become: true
  shell: killall supervisord
  ignore_errors: true

- name: start supervisord
  become: true
  shell: /usr/local/bin/supervisord
